Repository chas-academy/u05-imdb-clone-team4, pull requests merged in 2021-03, with the labels that each got.

#13 User authentication/login
  .env
  .vscode/settings.json
  app/Http/Middleware/CheckIfAdmin.php
  app/Models/User.php
  app/Providers/RouteServiceProvider.php
  composer.json
  composer.lock
  config/backpack/base.php
  config/backpack/permissionmanager.php
  config/permission.php
  database/migrations/2020_03_31_114745_remove_backpackuser_model.php
  database/migrations/2021_02_17_140407_create_permission_tables.php
  resources/lang/vendor/backpack/ar/permissionmanager.php
  resources/lang/vendor/backpack/da_DK/permissionmanager.php
  resources/lang/vendor/backpack/de/permissionmanager.php
  resources/lang/vendor/backpack/el/permissionmanager.php
  resources/lang/vendor/backpack/en/permissionmanager.php
  resources/lang/vendor/backpack/es/permissionmanager.php
  resources/lang/vendor/backpack/fr/permissionmanager.php
  resources/lang/vendor/backpack/fr_CA/permissionmanager.php
  resources/lang/vendor/backpack/hu/permissionmanager.php
  resources/lang/vendor/backpack/id/permissionmanager.php
  resources/lang/vendor/backpack/it/permissionmanager.php
  resources/lang/vendor/backpack/lv/permissionmanager.php
  resources/lang/vendor/backpack/nl/permissionmanager.php
  resources/lang/vendor/backpack/pt/permissionmanager.php
  resources/lang/vendor/backpack/pt_br/permissionmanager.php
  resources/lang/vendor/backpack/ru/permissionmanager.php
  resources/lang/vendor/backpack/sr/permissionmanager.php
  resources/lang/vendor/backpack/tr/permissionmanager.php
  resources/lang/vendor/backpack/zh-Hant/permissionmanager.php
  resources/views/user.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  routes/web.php
Labels: backend, frontend

#17 User handling in pipeline
  .env
  app/Http/Middleware/CheckIfAdmin.php
  composer.json
  config/backpack/base.php
  config/backpack/permissionmanager.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
Labels: enhancement

#12 Scaffolding
  .vscode/settings.json
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/MovieController.php
  app/Http/Controllers/MovieList.php
  app/Http/Controllers/RegisteredUserController.php
  app/Http/Controllers/SignInController.php
  app/Http/Controllers/SignUpController.php
  app/View/Components/Footer.php
  app/View/Components/Header.php
  resources/views/admin_view.blade.php
  resources/views/components/footer.blade.php
  resources/views/components/header.blade.php
  resources/views/index.blade.php
  resources/views/movie.blade.php
  resources/views/movie_list.blade.php
  resources/views/registered_user.blade.php
  resources/views/sign_in.blade.php
  resources/views/sign_up.blade.php
  routes/web.php
Labels: scaffolding

#19 Register user
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/RegisteredUserController.php
  app/Http/Controllers/Admin/SignInController.php
  app/Http/Controllers/Admin/SignUpController.php
  app/Http/Controllers/Auth/ConfirmPasswordController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/VerificationController.php
  app/Http/Controllers/Movie/MovieController.php
  app/Http/Controllers/Movie/MovieList.php
  app/Http/Controllers/User/LoginController.php
  app/Http/Controllers/User/LogoutController.php
  app/Http/Controllers/User/RegisterUserController.php
  app/Http/Controllers/User/RegisteredUserController.php
  app/Http/Controllers/User/TermsController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/View/Components/Footer.php
  app/View/Components/Header.php
  composer.json
  composer.lock
  package.json
  resources/css/app.css
  resources/js/app.js
  resources/js/bootstrap.js
  resources/sass/app.scss
  resources/views/admin_view.blade.php
  resources/views/components/footer.blade.php
  resources/views/components/header.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/movies/list.blade.php
  resources/views/movies/movie.blade.php
  resources/views/navigation/main.blade.php
  resources/views/registered_user.blade.php
  resources/views/sign_in.blade.php
  resources/views/sign_up.blade.php
  resources/views/user.blade.php
  resources/views/user/index.blade.php
  resources/views/user/login.blade.php
  resources/views/user/register.blade.php
  resources/views/user/terms.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  webpack.mix.js
Labels: backend, database, enhancement, frontend

#30 added color.scss
  resources/sass/app.scss
  resources/sass/layout/_colors.scss
  resources/sass/layout/_list.scss
Labels: frontend

#35 Secure nginx (local HTTPS)
  .env
  .env.example
  docker-compose.yml
  docker-compose/nginx/Dockerfile
  docker-compose/nginx/ssl/generate-ssl.sh
  docker-compose/nginx/ssl/vhost.sh
  docker-compose/nginx/travellist.conf
  docker-compose/php/Dockerfile
  package.json
Labels: enhancement

#34 New classes for buttons
  resources/sass/app.scss
  resources/sass/layout/_buttons.scss
  resources/sass/layout/_colors.scss
Labels: enhancement, frontend

#36 Suggestion to some color scheme changes
  resources/sass/app.scss
  resources/sass/custom/_colors.scss
  resources/sass/custom/_styling.scss
  resources/sass/custom/_variables.scss
  resources/sass/layout/_colors.scss
  resources/sass/layout/_footer.scss
  resources/sass/layout/_list.scss
Labels: enhancement, frontend

#40 Versioning fa npm
  package.json
  resources/js/app.js
  resources/sass/app.scss
  resources/views/layouts/header.blade.php
  webpack.mix.js
Labels: enhancement

#39 Suggestions for new file structure
  app/Http/Controllers/Movie/MovieController.php
  app/Http/Controllers/Movie/MovieList.php
  app/Http/Controllers/User/LoginController.php
  app/Http/Controllers/User/RegisterUserController.php
  app/Http/Controllers/User/RegisteredUserController.php
  resources/sass/layout/_buttons.scss
  resources/views/components/cards.blade.php
  resources/views/components/carousel.blade.php
  resources/views/errors/400.blade.php
  resources/views/errors/401.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/405.blade.php
  resources/views/errors/408.blade.php
  resources/views/errors/429.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/503.blade.php
  resources/views/includes/footer.blade.php
  resources/views/includes/head.blade.php
  resources/views/includes/header.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/default.blade.php
  resources/views/layouts/error.blade.php
  resources/views/movies/list.blade.php
  resources/views/movies/movie.blade.php
  resources/views/pages/account.blade.php
  resources/views/pages/home.blade.php
  resources/views/pages/lists.blade.php
  resources/views/pages/login.blade.php
  resources/views/pages/movie.blade.php
  resources/views/pages/register.blade.php
  resources/views/pages/terms.blade.php
  routes/web.php
Labels: enhancement

#46 Card fix
  resources/sass/app.scss
  resources/sass/layout/_cards.scss
  resources/sass/layout/_list.scss
  resources/views/components/cards.blade.php
  resources/views/includes/cards.blade.php
  resources/views/pages/home.blade.php
Labels: frontend

#47 Migration initial accounts and roles
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/RegisteredUserController.php
  app/Http/Controllers/Admin/SignInController.php
  app/Http/Controllers/Admin/SignUpController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  config/backpack/base.php
  database/migrations/2021_02_17_140407_create_permission_tables.php
  database/seeders/UserSeeder.php
  resources/views/pages/login.blade.php
  routes/web.php
Labels: backend, database, enhancement

#49 Admin role on register
  app/Http/Controllers/Admin/Auth/RegisterAdminController.php
  app/Http/Controllers/Auth/ConfirmPasswordController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/VerificationController.php
  routes/web.php
Labels: backend, bug, database, enhancement

#50 Homepage controller
  app/Http/Controllers/Movie/MovieList.php
  app/Http/Controllers/Page/HomePageController.php
  app/Http/Controllers/User/LogoutController.php
  resources/views/includes/header.blade.php
  routes/web.php
Labels: enhancement, frontend

#52 Heroku GD lib debug
  composer.lock
Labels: bug

#53 Seed users once
  database/migrations/2021_02_17_140407_create_permission_tables.php
  database/migrations/2021_03_23_184336_create_review_user_table.php
  database/migrations/2021_03_23_184337_create_movie_review_table.php
  database/migrations/2021_03_24_080416_create_movies_table.php
  database/migrations/2021_03_24_080417_create_reviews_table.php
Labels: backend, database

#54 Base 64 images
  .blueprint
  app.json
  app/Http/Controllers/Admin/MovieCrudController.php
  app/Models/Movie.php
  database/factories/Models/MovieFactory.php
  database/migrations/2021_03_24_095741_create_movies_table.php
  database/migrations/2021_03_24_095742_create_reviews_table.php
  draft.yml
  public/covers/6c3c848ff76d5146d02851590cb0abd0.jpg
  public/covers/7b636652d5c157b40916ba3cf536e3e4.jpg
  resources/views/pages/movie.blade.php
Labels: backend, bug, database, enhancement, frontend

#55 move backpack install to app.json
  app.json
Labels: backend, database

#58 Movie search
  app/Http/Controllers/ComponentSearchController.php
  resources/js/app.js
  resources/js/search.js
  resources/views/includes/head.blade.php
  resources/views/includes/header.blade.php
  resources/views/layouts/default.blade.php
  routes/web.php
Labels: enhancement, frontend

#59 Review approval & movie seeder
  .blueprint
  app/Http/Controllers/Admin/ReviewCrudController.php
  app/Http/Controllers/Movie/MovieController.php
  app/Http/Controllers/Movie/MovieReviewWriteController.php
  app/Http/Requests/ReviewRequest.php
  app/Models/Movie.php
  app/Models/Review.php
  database/migrations/2021_03_25_185645_create_movies_table.php
  database/migrations/2021_03_25_185646_create_reviews_table.php
  database/seeders/MovieSeeder.php
  draft.yml
  resources/views/components/review-card.blade.php
  resources/views/pages/movie.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  routes/web.php
  seeder-images/justice-league-2021.jpg
  seeder-images/raya-2021.jpg
Labels: backend, database, enhancement, frontend

#60 Add review list count for public status
  app/Http/Controllers/Movie/MovieController.php
  resources/views/pages/movie.blade.php
Labels: enhancement, frontend

#61 Movie styling fix
  resources/sass/layout/_header.scss
  resources/views/components/review-card.blade.php
  resources/views/pages/movie.blade.php
Labels: frontend

#64 Fix styling of review-cards and other minor fixes
  app/Http/Controllers/Movie/MovieController.php
  resources/sass/custom/_styling.scss
  resources/sass/layout/_cards.scss
  resources/sass/layout/_footer.scss
  resources/views/components/review-card.blade.php
  resources/views/pages/movie.blade.php
  resources/views/pages/review-write.blade.php
Labels: frontend

#66 CRUD bulk operations
  app/Http/Controllers/Admin/MovieCrudController.php
  app/Http/Controllers/Admin/ReviewCrudController.php
Labels: backend, database, enhancement

#67 Movie seeder update
  database/seeders/MovieSeeder.php
  seeder-images/american-history-x-1998.jpg
  seeder-images/apocalypse-now-1979.jpg
  seeder-images/birds-the-1963.jpg
  seeder-images/city-of-god-2002.jpg
  seeder-images/clockwork-orange-a-1971.jpg
  seeder-images/fight-club-1999.jpg
  seeder-images/forrest-gump-1994.jpg
  seeder-images/godfather-the-1972.jpg
  seeder-images/godfather-the-part-II-1974.jpg
  seeder-images/godzilla-2014.jpg
  seeder-images/good-fellas-1990.jpg
  seeder-images/good-the-bad-and-the-ugly-the-1966.jpg
  seeder-images/green-mile-the-1999.jpg
  seeder-images/inception-2010.jpg
  seeder-images/intouchables-the-2011.jpg
  seeder-images/la-femme-nikita-1990.jpg
  seeder-images/leon-the-professional-1994.jpg
  seeder-images/lord-of-the-rings-the-return-of-the-king-the-2003.jpg
  seeder-images/once-upon-a-time-in-america-1984.jpg
  seeder-images/one-flew-over-the cuckoos-nest-1975.jpg
  seeder-images/pulp-fiction-1994.jpg
  seeder-images/schindlers-list-1993.jpg
  seeder-images/se7en-1995.jpg
  seeder-images/shawshank-redemption-the-1994.jpg
  seeder-images/silence-of-the-lambs-the-1991.jpg
  seeder-images/soul-2020.jpg
  seeder-images/spirited-away-2001.jpg
  seeder-images/usual-suspects-the-1995.jpg
Labels: backend, database, enhancement, frontend

#69 Delete review btn
  resources/views/errors/405.blade.php
  routes/web.php
Labels: bug, frontend

#70 fix: reverted to {id} from {movie} in review post route
  routes/web.php
Labels: backend, bug, database, frontend

#68 style for cards on home- and account page
  resources/sass/layout/_cards.scss
  resources/views/components/cards.blade.php
  resources/views/components/watchlist.blade.php
  resources/views/includes/cards.blade.php
  resources/views/pages/account.blade.php
  resources/views/pages/home.blade.php
Labels: frontend

#71 Convert search string to lowercase
  resources/js/search.js
Labels: bug, enhancement, frontend

#74 Header style
  resources/sass/layout/_header.scss
  resources/views/includes/header.blade.php
Labels: frontend

#81 Fixed carousel
  resources/sass/app.scss
  resources/sass/custom/_colors.scss
  resources/sass/custom/_styling.scss
  resources/sass/layout/_app.scss
  resources/sass/layout/_carousel.scss
  resources/sass/layout/_footer.scss
  resources/sass/layout/_header.scss
  resources/sass/layout/_login.scss
  resources/sass/layout/_main.scss
  resources/sass/layout/_movie.scss
  resources/views/components/carousel.blade.php
  resources/views/includes/head.blade.php
  resources/views/pages/home.blade.php
  resources/views/pages/login.blade.php
  resources/views/pages/register.blade.php
Labels: frontend

#78 Reviews in account
  app/Http/Controllers/Movie/MovieController.php
  app/Http/Controllers/User/RegisteredUserController.php
  app/View/Components/account-movie-card.php
  app/View/Components/review-account.php
  resources/sass/layout/_cards.scss
  resources/views/components/review-account.blade.php
  resources/views/components/session-message.blade.php
  resources/views/pages/account.blade.php
  resources/views/pages/movie.blade.php
Labels: enhancement, frontend
